version: "3.9"
services:
  mysql:
    image: mysql:8.3
    container_name: txlab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: txlab
      MYSQL_USER: app
      MYSQL_PASSWORD: apppw
      TZ: Asia/Seoul
    ports:
      - "3307:3306"   # 호스트 3307 → 컨테이너 3306
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci",
      "--explicit_defaults_for_timestamp=ON"
    ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpw"]
      interval: 5s
      timeout: 3s
      retries: 20
