# =========================
# 공통 설정 (모든 프로필 공통)
# =========================
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    # @Transactional AOP 인터셉터: 경계 진입/종료/예외 흐름
    # 예: "Getting transaction for ...", "Completing transaction for ..."
    org.springframework.transaction.interceptor: TRACE

    # Hibernate가 실제로 실행한 SQL
    # 예: "select ...", "update wallet set ..."
    org.hibernate.SQL: DEBUG

    # Hibernate 6 파라미터 바인딩 값
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # JPA 트랜잭션 매니저: BEGIN/COMMIT/ROLLBACK, rollback-only, 참여/중단/재개(suspend/resume)
    # 예: "Creating new transaction ...", "Initiating transaction rollback"
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG

# =========================
# local 프로필 (도커 MySQL 접속)
# =========================
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/txlab?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: app
    password: apppw
  jpa:
    hibernate:
      ddl-auto: update

# =========================
# test 프로필 (Testcontainers 사용)
#  - 데이터소스는 테스트 설정 클래스에서 System.setProperty로 주입
#  - 스키마는 매 테스트마다 새로 생성/삭제
# =========================
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    # Testcontainers JDBC URL: 별도의 자바 설정 클래스 필요 없음
    url: jdbc:tc:mysql:8.3:///txlab?TC_TMPFS=/var/lib/mysql:rw
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway.enabled: false
  liquibase.enabled: false
